# Generated by Django 4.2.4 on 2023-10-21 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric_type', models.CharField(choices=[('Katrina', 'Katrina'), ('Blockout', 'Blockout'), ('Sheer', 'Sheer'), ('None', 'None')], max_length=250, null=True)),
                ('payment', models.CharField(choices=[('GCASH', 'GCASH'), ('CASH ON DELIVERY', 'CASH ON DELIVERY'), ('LBC', 'LBC'), ('OTHERS', 'OTHERS')], max_length=250, null=True)),
                ('price', models.PositiveIntegerField(null=True)),
                ('color', models.CharField(max_length=250, null=True)),
                ('product_tag', models.SmallIntegerField(choices=[(1, 'Blockout'), (2, '5-in-1 Katrina'), (3, '3-in-1 Katrina'), (4, 'Tieback Holder')])),
                ('set_tag', models.CharField(choices=[('5-in-1', '5-in-1'), ('3-in-1', '3-in-1'), ('Single', 'Single'), ('None', 'None')], max_length=250, null=True)),
                ('month_of_purhase', models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True)),
                ('qty', models.PositiveIntegerField(null=True)),
                ('count', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric', models.CharField(choices=[('Katrina', 'Katrina'), ('Blockout', 'Blockout'), ('Sheer', 'Sheer'), ('Korean', 'Korean')], max_length=250)),
                ('setType', models.CharField(choices=[('Singles', 'Singles'), ('3 in 1', '3 in 1'), ('4 in 1', '4 in 1'), ('5 in 1', '5 in 1')], max_length=250)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('qty', models.CharField(max_length=250)),
                ('unit', models.CharField(max_length=250)),
                ('price', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='customers/static/product_images')),
                ('stock', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fchub.category')),
            ],
        ),
        migrations.CreateModel(
            name='FleekyAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('login_time', models.DateTimeField(blank=True, null=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin',
            },
        ),
    ]
