# Generated by Django 4.2.4 on 2023-11-19 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fchub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricmaterial',
            name='fabric',
            field=models.CharField(choices=[('Katrina', 'Katrina'), ('Blockout', 'Blockout'), ('Sheer', 'Sheer'), ('Korean', 'Korean'), ('Brocade', 'Brocade')], max_length=250),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('fabric_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fchub.fabricmaterial')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fchub.material')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fchub.product')),
            ],
        ),
        migrations.CreateModel(
            name='FabricIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('unit', models.CharField(max_length=250)),
                ('fabric_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fchub.fabricmaterial')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fchub.material')),
            ],
        ),
    ]
