# Generated by Django 4.2.4 on 2023-11-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fchub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessfulOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100)),
                ('success_order_id', models.CharField(max_length=20, unique=True)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=250)),
                ('fabric', models.CharField(max_length=250)),
                ('setType', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('qty', models.PositiveIntegerField()),
                ('count', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
