# Generated by Django 4.2.4 on 2023-11-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fchub', '0002_successfulorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvdata',
            name='fabric',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
