# Generated by Django 4.2.4 on 2023-10-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fchub', '0003_rename_product_id_product_custom_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleekyadmin',
            name='custom_admin_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Custom Admin ID'),
        ),
    ]
