# Generated by Django 4.2.4 on 2023-10-23 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fchub', '0004_fleekyadmin_custom_admin_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fleekyadmin',
            name='custom_admin_id',
        ),
    ]
