# Generated by Django 4.2.4 on 2023-11-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fchub', '0004_curtainingredients_delete_fabricingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='curtainingredients',
            name='fabric_unit',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curtainingredients',
            name='grommet_unit',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curtainingredients',
            name='length_unit',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curtainingredients',
            name='rings_unit',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curtainingredients',
            name='thread_unit',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
