# Generated by Django 4.2.4 on 2023-11-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fchub', '0004_salesforcategory_salesforcolor_salesforlocation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesForWebData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric_type', models.CharField(max_length=250, null=True)),
                ('location', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=250, null=True)),
                ('set_type', models.CharField(max_length=250, null=True)),
                ('price', models.PositiveIntegerField(null=True)),
                ('gen_SalesID', models.CharField(max_length=20, null=True, unique=True)),
            ],
        ),
    ]
