# Generated by Django 4.2.4 on 2023-10-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fchub', '0005_remove_fleekyadmin_custom_admin_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleekyadmin',
            name='custom_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
