# Generated by Django 4.2.4 on 2023-11-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fchub', '0005_curtainingredients_fabric_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curtainingredients',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
