# Generated by Django 4.2.4 on 2023-11-05 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fchub', '0005_salesforwebdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracker',
            old_name='set_tag',
            new_name='setType',
        ),
    ]
