# Generated by Django 4.2.4 on 2023-11-05 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fchub', '0006_rename_set_tag_tracker_settype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesforwebdata',
            old_name='location',
            new_name='date',
        ),
    ]
