# Generated by Django 4.2.4 on 2023-11-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fchub', '0006_curtainingredients_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='curtainingredients',
            name='curtain_custom_id',
            field=models.CharField(blank=True, editable=False, max_length=15, unique=True),
        ),
    ]
