# Generated by Django 4.2.4 on 2023-11-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fchub', '0007_curtainingredients_curtain_custom_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curtainingredients',
            name='fabric',
            field=models.CharField(choices=[('Katrina', 'Katrina'), ('Blockout', 'Blockout'), ('Sheer', 'Sheer'), ('Korean', 'Korean'), ('Brocade', 'Brocade')], max_length=250),
        ),
    ]
