# Generated by Django 4.2.4 on 2023-10-27 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fchub', '0007_fleekyadmin_is_admin_fleekyadmin_is_customer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='analytics',
            new_name='Tracker',
        ),
    ]
