# Generated by Django 4.2.4 on 2023-11-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fchub', '0007_rename_location_salesforwebdata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesforwebdata',
            name='gen_SalesID',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
