# Generated by Django 4.2.4 on 2023-10-27 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fchub', '0008_rename_analytics_tracker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracker',
            old_name='month_of_purhase',
            new_name='month_of_purchase',
        ),
    ]
