# Generated by Django 4.2.4 on 2023-11-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fchub', '0008_alter_salesforwebdata_gen_salesid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesforwebdata',
            name='gen_SalesID',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
