# Generated by Django 4.2.4 on 2023-11-05 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fchub', '0009_alter_salesforwebdata_gen_salesid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesforwebdata',
            name='gen_SalesID',
        ),
    ]
