# Generated by Django 4.2.4 on 2023-10-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fchub', '0009_rename_month_of_purhase_tracker_month_of_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Csv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('csv_file', models.FileField(upload_to='fchub/csvs/')),
            ],
        ),
        migrations.CreateModel(
            name='CsvData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.CharField(max_length=20)),
                ('day', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('customerName', models.CharField(max_length=100)),
                ('setType', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('count', models.IntegerField()),
                ('price', models.CharField(max_length=20)),
            ],
        ),
    ]
