# Generated by Django 4.2.4 on 2023-10-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fchub', '0010_csv_csvdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv',
            name='csv_file',
            field=models.FileField(upload_to='fchub/csv/'),
        ),
    ]
