# Generated by Django 4.2.4 on 2023-11-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fchub', '0010_remove_salesforwebdata_gen_salesid'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesForFabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fabric', models.CharField(max_length=250)),
                ('generated_id', models.CharField(max_length=12, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SalesForProduct',
        ),
    ]
