# Generated by Django 4.2.4 on 2023-11-05 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fchub', '0011_salesforfabric_delete_salesforproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesforfabric',
            name='generated_id',
        ),
    ]
