# Generated by Django 4.2.4 on 2023-11-05 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fchub', '0012_remove_salesforfabric_generated_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesforcategory',
            name='generated_id',
        ),
    ]
