# Generated by Django 4.2.4 on 2023-11-06 11:26

from django.db import migrations
import fchub.custom_fields


class Migration(migrations.Migration):

    dependencies = [
        ('fchub', '0014_remove_salesforcolor_generated_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesforwebdata',
            name='color',
            field=fchub.custom_fields.CommaSeparatedCharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='salesforwebdata',
            name='fabric_type',
            field=fchub.custom_fields.CommaSeparatedCharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='salesforwebdata',
            name='set_type',
            field=fchub.custom_fields.CommaSeparatedCharField(max_length=250, null=True),
        ),
    ]
