# Generated by Django 4.2.4 on 2023-11-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fchub', '0015_alter_salesforwebdata_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesforwebdata',
            name='color',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='salesforwebdata',
            name='fabric_type',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='salesforwebdata',
            name='set_type',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
