# Generated by Django 4.2.4 on 2023-11-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fchub', '0016_alter_salesforwebdata_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesforwebdata',
            name='date',
            field=models.DateField(),
        ),
    ]
