# Generated by Django 4.2.4 on 2023-11-06 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fchub', '0018_remove_salesforwebdata_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesforcategory',
            name='price',
        ),
        migrations.RemoveField(
            model_name='salesforfabric',
            name='price',
        ),
    ]
