# Generated by Django 4.2.4 on 2023-11-06 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fchub', '0019_remove_salesforcategory_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesforcolor',
            name='price',
        ),
        migrations.RemoveField(
            model_name='salesforlocation',
            name='price',
        ),
    ]
