# Generated by Django 4.2.4 on 2023-11-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fchub', '0021_rename_location_salesforcolor_fabric'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesforlocation',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesforlocation',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
