# Generated by Django 4.2.4 on 2023-11-07 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fchub', '0022_salesforlocation_latitude_salesforlocation_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=250)),
                ('fabric', models.CharField(max_length=250)),
                ('setType', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('qty', models.PositiveIntegerField()),
                ('count', models.PositiveIntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
