# Generated by Django 4.2.4 on 2023-11-08 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fchub', '0024_cleantrainingsets_trainingsets_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleantrainingsets',
            name='name',
        ),
        migrations.RemoveField(
            model_name='cleantrainingsets',
            name='order_number',
        ),
        migrations.RemoveField(
            model_name='trainingsets',
            name='name',
        ),
        migrations.RemoveField(
            model_name='trainingsets',
            name='order_number',
        ),
    ]
