# Generated by Django 4.2.4 on 2023-11-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('page_views', models.PositiveIntegerField()),
                ('customer_id', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
