# Generated by Django 4.2.4 on 2023-10-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_alter_customer_options_customer_is_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='is_customer',
            field=models.BooleanField(default=True),
        ),
    ]
